- _quickguides/about.md
- _quickguides/create-tvapp.md
- _quickguides/create-wearableapp.md
- _quickguides/environment.md
- _quickguides/publish-tvapp.md
- _quickguides/publish-wearableapp.md
These files have been reviewed and edited and are ready to be merged with Samsung/Tizen.NET:
QuickGuides/about.md
QuickGuides/create-tvapp.md
QuickGuides/create-wearableapp.md
QuickGuides/environment.md
QuickGuides/publish-tvapp.md
> Please merge files at jboothman/Tizen .NET with Samsung/Tizen.NET.

- _posts/2019-01-02-welcome-to-tizen-posts.md
- _posts/2019-01-04-How-to-package-UI-and-service-apps.md
- _posts/2019-01-16-tizen-baseline-sdk.md
- _posts/2019-01-24-tv-emul-v5.md
- _quickguides/about.md
- _quickguides/create-tvapp.md
- _quickguides/create-wearableapp.md
- _quickguides/environment.md
- _quickguides/publish-tvapp.md
- _quickguides/publish-wearableapp.md
Pull request to add these newly edited files:
QuickGuides/quickguides.md
_posts/2019-01-02-welcome-to-tizen-posts.md
_posts/2019-01-04-How-to-package-UI-and-service-apps.md
_posts/2019-01-16-tizen-baseline-sdk.md
> Pull request to add reviewed and edited content

- _faq/general-questions.md
- _faq/wearable-review.md
- _pages/home.md
- _posts/2019-06-13-Using-Tizen-NET-Sdk-as-SDK-style.md
- _posts/2019-07-16-Connecting-TV-and-VisualStudio.md
Hi Jay - I did not see the images in the 2019-07-16-Connecting-TV-and-VisualStudio.md preview. They appeared as broken links.
Please review and merge these files from j.boothman/Tizen.NET to Samsung/Tizen.NET: general-questions.md, wearable-review.md, home.md, 2019-06-13-Using-Tizen-NET-Sdk-as-SDK-style.md, and 2019-07-16-Connecting-TV-and-VisualStudio.md
> Please review and merge these files

- _posts/2019-08-08-Adding a splash screen to your Tizen .NET application.md
Pull request to add the newly edited and revised "2019-08-08-Adding-a-splash-screen-to-your-TizenNET-application.md" file.
> Pull request to add edited content

- _posts/2019-09-16-how-to-set-image-borders.md
Merge j.boothman/Tizen .NET to add 2019-09-16-how-to-set-image-borders.md
> Please merge to add updated content

- _posts/2019-10-14-Update-TizenNETSdk-package.md
Add a new post noticing issue on VS version 16.3
> Add a new post noticing issue on VS version 16.3

- _posts/2019-11-20-Samsung-Developer-Conference-2019.md
Please update to add the edited 2019-11-20-Samsung-Developer-Conference-2019.md file.
> Please merge to add modified file

- _posts/2019-11-20-Samsung-Developer-Conference-2019.md
- _posts/2019-12-02-Build-an-Widget-application-for-Galaxy-Watch.md
Please merge jboothman/Tizen.NET with Samsung/Tien.NET to add edited  "_posts/2019-12-02-Build-an-Widget-application-for-Galaxy-Watch.md" file.
> Please merge to add edited file

- _posts/2019-12-16-Image-caching-with-FFImageloading.md
introduce FFImageLoading library
> Add a new post image caching

- _posts/2019-12-16-Image-caching-with-FFImageloading.md
Please merge the _posts/2019-12-16-Image-caching-with-FFImageloading.md file on jboothman/Tizen.NET with Samsung/Tizen.NET. I have two questions in the file; look for the phrases in paranethese that start with Question:.
> Update to _posts/2019-12-16-Image-caching-with-FFImageloading.md file 

- 2019-12-30-moving-notice.md
- 2020-01-16-grabbing-hardware-key-events.md
- _posts/2019-12-30-moving-notice.md
Reviewed, edited, and added "Moving Notice" and "Grabbing Hardware Key Events" files to jboothman/Tizen.NET. Request they be merged to Samsung/Tizen.NET.
> New files added.

- .github/workflows/build.yml
Fetch all commit history in CI build to calculate the commit distance.
> Fetch all commit history in CI build

- .github/workflows/build-workload.yml
- Push CI generated packages to Github Package Registry
> Add deploy job to workflow

- workload/build/Directory.Build.targets
- workload/build/Samsung.NET.Workload.Tizen.proj
Context: https://github.com/dotnet/designs/pull/188/files#diff-8fcaa29d8e6f00b34b3cb1830d93f33e75f04424780a66a3c658c7021048e74fR125
> Move WorkloadManifest.* files to data directory

- workload/build/Directory.Build.targets
- workload/build/Versions.props
- workload/src/Samsung.NET.Sdk.Tizen/WorkloadManifest.targets
- bump to dotnet-sdk 6.0.100-preview.5
- Add tizen to SdkSupportedTargetPlatformIdentifier 
- Use lowercase of sdk-manifests directory
> Merge preview.5 to main

- .github/workflows/build-workload.yml
- workload/Makefile
Add `test` target to test creating and building a tizen project using `tizen` workload
```sh
make test
```
> Add test target to Makefile

- workload/build/Versions.props
- Update dotnet sdk version to 6.0.100-rc.1.21427.28
> Bump to dotnet sdk 6.0.100-rc.1.21427.28

- README.md
Update the installation guide to use the workload-install script.
> Update README.md about using workload-install script

- workload/scripts/workload-install.ps1
`dotnet workload install` command does not allow 3rd-party workload installation. 
If this PR is merged, the `workload-install.ps` script 
- copies files of the workload packs to the dotnet sdk directory directly.
- adds `tizen` to the installed workload metadata.
> [workload] Copy workload packs to dotnet sdk directly

- workload/scripts/workload-install.ps1
If the already installed tizen workload, the old verison should be removed before installation of new version.
> [workload-install] Remove already installed workload

- workload/src/Samsung.Tizen.Sdk/Sdk/AutoImport.props
- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.Packaging.targets
This reverts commit beed478b1c15618f8e033fc9295cec534f3fddf6.
certificate error occurred during installation.
> Revert "Cleanup Samsung.Tizen.Sdk.Packaging.targets"

- workload/build/Versions.props
Bump dotnet sdk to 6.0.200-preview.22063.5
> [workload] Bump dotnet sdk to 6.0.200-preview.22063.5

- workload/scripts/workload-install.ps1
- workload/scripts/workload-install.sh
> [workload] Fix install script

- workload/build/Versions.props
- workload/scripts/workload-install.ps1
- workload/scripts/workload-install.sh
[workload] Bump dotnet sdk to 6.0.200-preview.22063.5
[workload] Fix install script
> [workload] bump up and fix script

- workload/build/Versions.props
[workload] Fix tizen workload version
from 7.0.0 to 7.0.100
> [workload] Fix tizen workload version

- workload/src/Samsung.Tizen.Build.Tasks/Signer/Xmldsig.cs
- workload/src/Samsung.Tizen.Sdk/Sdk/AutoImport.props
- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.Packaging.targets
Re-submit the reverted commit (#127)
- Simplify usages of path variables
- Add EnableDefaultTizenItems property
- Fix a bug of Signer
> Cleanup Samsung.Tizen.Sdk.Packaging.targets

- workload/src/Samsung.Tizen.Build.Tasks/CheckApiVersion.cs
- workload/src/Samsung.Tizen.Build.Tasks/GetManifestInfo.cs
- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.Packaging.targets
- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.Versions.targets
- workload/src/Samsung.Tizen.Templates/tizen/tizen-manifest.xml
> [workload] Add check api version

- README.md
- workload/scripts/README.md
Update README for install script to add description of a new install option `-t`.
> Update README for Install script

- workload/build/Versions.props
> Bump dotnet sdk to 6.0.300

- workload/scripts/workload-install.ps1
- workload/scripts/workload-install.sh
Update scripts to create the `.NET SDK manifest` directory required for tizen workload installation
> [script] create sdk manifest directory

- workload/build/Versions.props
Bump up dotnet sdk band to 6.0.400
Bump up TizenFX version to 10.0.0.17172
> Bump up dotnet sdk band 6.0.400

- workload/build/Versions.props
Bump up TizenWorkloadVersion same as dotnet sdk version band.
> Bump up TizenWorkloadVersion

- workload/scripts/workload-install.ps1
- workload/scripts/workload-install.sh
tizen workload version 7.0.303 for dotnet sdk version 6.0.300
> Update latest version map

- workload/scripts/workload-install.ps1
- workload/scripts/workload-install.sh
- Change support dotnet sdk version from only 6 to 6 or later.
> [script] Fix support version

- workload/Config.mk
- workload/Makefile
- workload/NuGet.config
- workload/scripts/workload-install.ps1
- workload/scripts/workload-install.sh
Sync script and makefile from net7.0 to main
> Sync script and makefile

- workload/scripts/workload-install.ps1
- workload/scripts/workload-install.sh
Update message output in workload install script to show the installation is done.
> Update Install status output

- workload/scripts/workload-install.sh
- Update LatestVersionMap
- Add Update-all-workloads option
- Sync with ps1 script : #193
> [Script] Update install script to add new option

- workload/build/Versions.props
Bump up dotnet sdk version to 7.0.100-rc.2.22454.1
> Bump up dotnet sdk version

- workload/scripts/workload-install.ps1
- workload/scripts/workload-install.sh
- Add update all
- Update installing metadata
- Update version map
> Sync scripts

- workload/scripts/workload-install.ps1
- workload/scripts/workload-install.sh
Update version map for dotnet sdk version 7.0.100
> Update version map

- workload/NuGet.config
- workload/build/Samsung.Tizen.Ref.proj
- workload/build/Versions.props
- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.Versions.targets
- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.targets
- workload/src/Samsung.Tizen.Templates/tizen/TizenApp1.csproj
To prepare for the release of tizen workload for net8.0.
> Initialize net8.0 branch

- workload/build/Versions.props
- workload/scripts/workload-install.ps1
- workload/scripts/workload-install.sh
- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.NuGet.targets
- workload/src/Samsung.Tizen.Templates/tizen/.template.config/template.json
Prepare `tizen workload 7.0.105` for `dotnet sdk 8.0.100-preview.2`
> Prepare tizen workload 7.0.105

- workload/build/Versions.props
- workload/scripts/workload-install.ps1
- workload/scripts/workload-install.sh
- Bump dotnet sdk 8.0.100-preview.3
> Bump dotnet sdk 8.0.100-preview.3

- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.Versions.targets
- workload/src/Samsung.Tizen.Templates/tizen/TizenApp1.csproj
- workload/src/Samsung.Tizen.Templates/tizen/tizen-manifest.xml
- Update the default target platform version to `7.0`.
- `7.0` is the latest public released target platform version.
- Update `KnownFrameworkReference` to target the `TargetFramework`
> Update default target platform version - net6.0

- workload/src/Samsung.Tizen.Build.Tasks/MergeManifest.cs
Fix Manifest merging issue
Related Issue : https://github.sec.samsung.net/RS-TizenStudio/home/issues/500
> Fix Manifest merging issue
