- workload/build/Directory.Build.targets
Fixes the problem that the template copied to template-packs is not recognized.
issue: https://github.com/dotnet/templating/issues/3110
> Copy templates nupkg to lowercase path

- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.Versions.in.targets
`IsTrimmable` property is not necessary because the Samsung.Tizen provides only the framework-dependent deploy model.
> Remove unnecessary IsTrimmable property

- workload/Config.mk
- workload/Makefile
- workload/build/Versions.props
- workload/src/Samsung.NET.Sdk.Tizen/WorkloadManifest.in.json
- workload/src/Samsung.Tizen.Build.Tasks/GetManifestInfo.cs
- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.After.targets
- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.Applications.targets
- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.Common.targets
- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.Packaging.targets
- Add a target named `Install` and `Run` to Samsung.Tizen.Sdk.Applications.targets.
- GetManifestInfo task provides the first application's information
- Bump to dotnet sdk 6.0.100-preview.7
> Add "Run" target to run tizen application by using SDB

- workload/NuGet.config
- workload/scripts/README.md
- workload/scripts/workload-install.ps1
- workload/scripts/workload-install.sh
This script installs the Tizen workload manifest files and packs to the dotnet sdk location.
On Linux:
```
workload-install.sh [-v <Version>] [-d <Dotnet SDK Location>]
```
On Windows:
```
workload-install.ps1 [-v <Version>] [-d <Dotnet SDK Location>]
```
If this script is executed in CI environment, you can use `curl` to download the script and execute it.
```
curl -sSL https://raw.githubusercontent.com/Samsung/Tizen.NET/main/workload/scripts/workload-install.sh | bash
```
or
```
curl -sSL https://raw.githubusercontent.com/Samsung/Tizen.NET/main/workload/scripts/workload-install.sh | bash -s -- -v <version> -d <dotnet sdk location>
```
> Add scripts for installation workload manifest files

- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.Packaging.targets
In case of reference a package using Tizen.NET 4.0.0, the tpk includes all runtime assets of the Tizen.NET package in self-contained build. To resolve this problem, the PackageConflictPlatformManifests is always set.
> Exclude assets written in PlatformManifests of Targeting pack always

- workload/scripts/workload-install.ps1
- workload/scripts/workload-install.sh
If `DOTNET_ROOT` environment variable exists and the dotnet installation directory is not set by using `-d` option, 
The installation script will try to install the workload to `DOTNET_ROOT` path first.
> [scripts] Use DOTNET_ROOT at installation

- workload/scripts/workload-install.ps1
Without quotes, empty envvars will throw:
```
> .\workload-install.ps1
Test-Path: C:\Projects\Maui\workload-install.ps1:62
Line |
62 |      if (Test-Path $Env:DOTNET_ROOT) {
|          ~~~~~~~~~~~~~~~~~~~~~~~~~~
| Value cannot be null. (Parameter 'The provided Path argument was null or an empty collection.')
```
> Make sure paths are not null

- workload/build/Versions.props
- Bump dotnet sdk to 6.0.100-rc.1.21458.32
> Bump dotnet sdk to 6.0.100-rc.1.21458.32

- workload/scripts/workload-install.ps1
- Fix `workload-install.ps1` to create `template-packs` directory if not exists.
> Create template-packs directory if not exists

- workload/build/Versions.props
- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.targets
Skip setting `FrameworkReference` for `Samsung.Tizen.Ref` package  when `DisableImplicitTizenReferences` is `true`.
It allows applications/libraries to refer the TizenFX reference assemblies from the `PackageReference`, not the assemblies provided by the workload. It can be used in GBS build that require use of the latest TizenFX.
```xml
<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
<TargetFramework>net6.0-tizen</TargetFramework>
<OutputType>Exe</OutputType>
<DisableImplicitTizenReferences>true</DisableImplicitTizenReferences>
</PropertyGroup>
<ItemGroup>
<PackageReference Include="Tizen.NET" Version="10.0.0.16958" />
</ItemGroup>
</Project>
```
> Add DisableImplicitTizenReferences property

- workload/src/Samsung.Tizen.Build.Tasks/ResourceXmlWriter.cs
- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.Packaging.targets
Refactor ResourceXmlWriter task
- Apply `res/contents/<lang_code>` and `res/contents/<dpi>` folders to `res/res.xml`
- Use `Path.Combine` instead of string concatenation for paths.
- Include res/res.xml file to the tpk package.
- Optimize for-loop
> [workload] Refactor ResourceXmlWriter task

- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.After.targets
Nuget workaround `Samsung.Tizen.Sdk.NuGet.targets` for supporting legacy TFM should be removed, since we now have dotnet/installer with `net6.0-tizen` precedence support.
However, this is still required when we want Visual Studio 2019 on Windows to continue working for .NET6 projects.
> Support legacy TFM in condition

- workload/src/Samsung.Tizen.Sdk/Sdk/AutoImport.props
- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.Packaging.targets
This PR fixes` Samsung.Tizen.Sdk.Packaging.targets` to include essential items when packaging Tizen tpk.
- Maui Tizen application now excludes all assets when the `EnableDefaultTizenItems` option is set to `false`.
- The default value of `EnableDefaultTizenItems`  for Maui Singleproject is `false`.
- The purpose of MAUI is to manage MAUI assets by itself.
- Take following Tizen items out of `EnableDefaultTizenItems` option block, and add them as default items.
- `tizen-manifest.xml` : essential item.
- `lib/` : This is not managed by Maui.
- Always Include followings. Default items will also be added to followings when option is on.
- @(TizenResource)
- @(TizenSharedResource)
- @(TizenTpkUserIncludeFiles)
> Fix Samsung.Tizen.Sdk.Packaging.targets

- workload/scripts/workload-install.ps1
- workload/scripts/workload-install.sh
Update Tizen workload install scripts to get `.NET SDK version band` based on installed dotnet.
Updated scripts will
- use installed `dotnet` on given or default path to get version
- reformat the version to version band (ex: `6.0.100` `6.0.200`)
- use version band to download Tizen manifest and install workload
- Exit quietly when local dotnet version is not .NET 6.
> Update workload install scripts

- workload/scripts/workload-install.sh
This PR update the logic to find an installed dotnet path.
1.  Check `DOTNET_ROOT` environement path
2.  Check a default dotnet path for linux `/usr/share/dotnet`.
3.  Check a default dotnet path for macos `/usr/local/share/dotnet`.
4.  Check dotnet link path on a machine.
> Add dotnet installation path candidates

- workload/scripts/workload-install.ps1
- workload/scripts/workload-install.sh
Add a new option '-t'  for Tizen workload installation.
`-t` option is used to modify an install path for a specified dotnet version band folder. 
Default behavior without `-t` option is to install workload in a corresponding dotnet version band folder.
For example, you can install a workload(`7.0.100-preview.6.19`) belonging to dotnet version band `6.0.200` to  `6.0.300` folder.
```sh
~$ ./workload-install.ps1 -v 7.0.100-preview.6.19 -t 6.0.300
```
The workload version (`7.0.100-preview.6.19`) still should be one in the installed dotnet version band on a local machine.
The purpose of providing a new option is to test and verify MAUI on a next version of dotnet version band.
> Add install option: target version band

- README.md
- workload/scripts/README.md
including .NET6 -> .NET 6, MacOS -> macOS, Linux/MacOS -> Linux / macOS
> product name spelling and grammar corrections

- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.Packaging.targets
- Do not print ` %(TizenTpkFiles.Identity)` no more.
- Use `Error` if faild to create tpk.
> Update tpk packaging.tagets message

- workload/scripts/workload-install.sh
Update workload install script to fix an issue occurred on macOS.
macOS uses the old version of bash, so the latest version map should be in different format.
> Update bash install script

- workload/scripts/workload-install.ps1
- workload/scripts/workload-install.sh
Applying [.NET SDK Workload Preview Bands policy](https://github.com/dotnet/sdk/blob/main/documentation/general/workloads/workload-preview-bands.md) updated from Net 7.0. This PR changes dotnet target version band directory which is located under `dotnet/sdk-manifests/[target version band]`.
> Because of this, in .NET 7 we are changing the definition of the SDK band to include the first two components of the SDK version prerelease specifier, if present. So the SDK band for 7.0.100-preview.1.12345 would be 7.0.100-preview.1, and the SDK band for 7.0.100-rc.2.21505.57 would be 7.0.100-rc.2.
Dotnet featured version band for preview version is now include the first two components of SDK version like below.
```
"6.0.100" -> "6.0.100"
"10.0.512" -> "10.0.500"
"7.0.100-preview.1.12345" -> …
```
> [NET 7.0] Apply featured version band

- workload/Config.mk
Fix manifest directory name for net 7.0
Changed manifest dir name from `{major-version}.{minor-version}.{version-band} `
to `{major-version}.{minor-version}.{version-band}-{pre-release}.{pre-release-version}`
> Fix manifest directory name for net 7.0

- workload/build/Samsung.NET.Sdk.Tizen.proj
Update Hotfix (https://github.com/Samsung/Tizen.NET/commit/a325174b2f5e2ab6412b3b1beec0a5dcfa558a46) which modified dotnet version band to hard coded value for the urgent NET 7.0 workload release.
This PR gets back to this to the formal code that can now also cover the featured version band to support NET 7.0.
> Update Hotfix to formal code

- workload/NuGet.config
- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.Versions.targets
- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.targets
- workload/src/Samsung.Tizen.Templates/tizen/.template.config/template.json
- Support building NET 6.0 (net6.0-tizen TFM) application on .NET 7.0.
- Use the Tizen ref released in the stable dotnet sdk 6.0.300 reference when build net6.0 application in .NET 7.0
- Support '--framework" option to Tizen template to provide net6.0 template.
- ~$ dotnet new tizen --framework net6.0 
- ~$ dotnet new tizen --framework net7.0
> [net7.0] Enable net6.0 build on net7.0

- .github/workflows/build-workload.yml
- workload/build/Versions.props
- workload/scripts/workload-install.ps1
- workload/scripts/workload-install.sh
- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.Versions.targets
- Bump up dotnet sdk version to `7.0.100-preview.7.22329.1`
- Update the latest version map.
- Add `net7.0` branch to trigger an Action
> [.NET7] Bump up dotnet sdk to preview7

- workload/Config.mk
This PR changes getting branch name used for creating nuget package in CI or local test environment to fix issue caused when the branch name has `/` symbol.
`main` -> `main`
`heads/net7.0` -> `net7.0`
`releases/6.0.0` ->`6.0.0`
In the CI or the local test environment , we create the special version to be used in the test.
However, for the branches other than main branch would have branch HEAD, for example `heads/net7.0`, `releases/xxxx `.
`/` symbol in the branchs causes issues when create the nuget packages.
> Fix version issue for net7 in CI environment

- workload/scripts/workload-install.ps1
Problem : Install break occurred when reinstall workload.
Cause : manifest directory remaining after workload uninstall.
Solution : Add check workload installed as same version.
> Add check workload installed

- workload/build/Versions.props
Bump up dotnet sdk version to `7.0.100-rc.1.22362.32`
> [.NET7] Bump up dotnet sdk version to rc1

- workload/scripts/workload-install.ps1
- Adding a new option `-u` (UpdateAllWorkloads) that updates Tizen workloads to the latest for all installed dotnet sdks on the machine.
- Example: `~$ workload-install.ps1 -u`
- When `-u` option is used, `-v` (Version) and `-t` (DotnetTargetVersionBand) options are ignored.
- Postpone checking permission step `Ensure-Directory` for not testing until it is really needed.
- This will prevent occurring an exception on VS launch with Tizen vsix installed.
- Remove output when creating a new folder
- Update Latest version map
> Update install script to add new feature

- workload/scripts/workload-install.sh
Fix `workload-install.sh` script 
- If there are several SDKs, for workload updates, the current .NET SDK must be changed.
- To solve the above problem, `global.json` file will be generated and deleted.
> Fix install script

- .github/workflows/release-workload.yml
Remove a step of release workflow about pusing windows .msi file to S3 bucket.
> Remove a workflow step about pusing msi to S3

- workload/scripts/workload-install.ps1
- workload/scripts/workload-install.sh
This PR updates the install steps for NET7.0 in order to fix an issue.
Issue: Installed Tizen workload was not on the installed workload list.
Fixed: For meta data marker file path above NET7.0 does NOT include any preview specifier.
> Update installing metadata for NET7.0

- workload/build/Samsung.Tizen.Ref.proj
- workload/src/Samsung.Tizen.Ref/data/PlatformManifest.txt
- workload/src/Samsung.Tizen.Ref/runtime.json
This PR
- adds `runtime.json` including Tizen RID information
-  packages the file to the root folder of Samsung.Tizen.Ref package
This PR will make it possible to use Tizen7.0.0 related RIDs until https://github.com/dotnet/runtime/pull/76600 is safely merged and released.
> Add RID information to Samsung.Tizen.Ref

- workload/Makefile
- workload/build/Versions.props
- Update dotnet sdk setup path as dotnet sdk 7.0.100 stable is not provided through the install script.
- Update TizenFX version to `10.0.0.17508` which is expected to be for Tizen 7.0.
> Workaround for dotnet sdk 7.0.100

- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.Versions.targets
- workload/src/Samsung.Tizen.Templates/tizen/TizenApp1.csproj
- workload/src/Samsung.Tizen.Templates/tizen/tizen-manifest.xml
- Update the default target platform version to `7.0`.
- `7.0` is the latest public released target platform version.
- Update `KnownFrameworkReference` to target the `TargetFramework`
- Update TFM on Sample `net7.0-tizen7.0`
> Update default target platform version - net7.0

- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.Versions.targets
- workload/src/Samsung.Tizen.Templates/tizen/TizenApp1.csproj
- workload/src/Samsung.Tizen.Templates/tizen/tizen-manifest.xml
- Update the default target platform version to `7.0`.
- `7.0` is the latest public released target platform version.
- Update `KnownFrameworkReference` to target the `TargetFramework`
- Update TFM on Sample to `net8.0-tizen7.0`
> Update default target platform version - net8.0

- workload/scripts/workload-install.sh
> Results vary by SDK version
The dotnet workload commands operate in the context of specific SDK versions. Suppose you have both .NET 6.0.100 SDK and .NET 6.0.200 SDK installed. The dotnet workload commands will give different results depending on which SDK version you select. This behavior applies to major and minor version and feature band differences, not to patch version differences. For example, .NET SDK 6.0.101 and 6.0.102 give the same results, whereas 6.0.100 and 6.0.200 give different results. You can specify the SDK version by using the [global.json file](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json) or the --sdk-version option of the dotnet workload commands.
According to [the documentation](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload- …
> fix: Use dotnet workload install --sdk-version instead global.json in scripts.

- workload/scripts/workload-install.sh
This reverts commit #259 
due to https://github.com/dotnet/docs/issues/37498.
> Revert #259

- .github/workflows/build-workload.yml
- samples/dotnet-podcasts/src/Services/Podcasts/Podcast.API/Podcast.API.csproj
- samples/dotnet-podcasts/src/Services/Podcasts/Podcast.Ingestion.Worker/Podcast.Ingestion.Worker.csproj
- workload/Config.mk
- workload/build/Versions.props
- workload/scripts/workload-install.ps1
- workload/scripts/workload-install.sh
- workload/src/Samsung.NETCore.App.Runtime/data/RuntimeList.xml
- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.NuGet.targets
- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.Versions.targets
- workload/src/Samsung.Tizen.Sdk/targets/Samsung.Tizen.Sdk.targets
- workload/src/Samsung.Tizen.Templates/tizen/.template.config/template.json
Prepare tizen workload version `8.0.131` for dotnet SDK `9.0.100-alpha.1.23617.1`.
Update
- Tizen workload version `8.0.131`
- Dotnet sdk version`9.0.100-alpha.1.23617.1`
- MicrosoftDotNetBuildTasksFeedPackageVersion `9.0.0-beta.23614.6`
- Referenced TizenFX API11 `11.0.0.18033`
- Support `net9.0-tizen8.0` tfm
> Update net9.0 support

- workload/src/Samsung.Tizen.Build.Tasks/MergeManifest.cs
Fix merge manifest error when main project doesn't have privileges and acount.
Updated code is following
```c#
else if (subapp.Name.LocalName == "privileges")
{
if (mainDoc.Root.Element(ns + "privileges") == null)
{
mainDoc.Root.Add(subapp);
}
else
{
mainDoc.Root.Element(ns + "privileges").Add(subapp.Descendants(ns + "privilege"));
}
}
else if (subapp.Name.LocalName == "account")
{
if (mainDoc.Root.Element(ns + "account") == null)
{
mainDoc.Root.Add(subapp);
}
else
{
mainDoc.Root.Element(ns + "account").Add(subapp.Descendants(ns + "account-provider"));
}
}
```
> Fix merge manifest error

- workload/scripts/workload-install.ps1
- workload/scripts/workload-install.sh
> Fix NuGet API calls in install script

- .github/workflows/release-workload.yml
- Deprecated actions runner image Ubuntu20.04
- https://github.com/actions/runner-images/issues/11101
> [Actions] Update runner image Ubuntu22.04
